### ISSUE TITLE
It seemed that the item_splitter not working properly at 1.16.5

### ISSUE THREAD

**Issue by GreenSandX** [Da-Technomancer/Essentials#61] opened 2021-07-16 08:36 UTC
The item_splitter alway putout items In a ratio of 2/3 ,and keep the initial item transfer direction and distance ,even if use a wrench,put in the redstone signal, or remove the extended item_chute, Yes, even out of thin air

if I reenter the save ,that will update the item transfer direction and distance just once , and 2/3 still

forge 36.1.0 , moded just by essentials 2.11.0 and patchouli 53.1

**Comment by Da-Technomancer** [comment] 2021-07-16 13:09
I'm not able to reproduce this issue.
Could you send a picture of your exact setup?
Also, does breaking and replacing the splitter fix it?

**Comment by GreenSandX** [comment] 2021-07-16 14:21
At 2021-07-16 21:09:46, "Max M" ***@***.***> wrote:

I'm not able to reproduce this issue.
Could you send a picture of your exact setup?
Also, does breaking and replacing the splitter fix it?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

从网易163邮箱发来的超大附件
21716.png (6.4M, 2021年7月31日 22:21 到期)
在线预览 | 下载

**Comment by Da-Technomancer** [comment] 2021-07-16 23:21
Your attachment didn't send properly, I think because you replied to the issue by email.

**Comment by GreenSandX** [comment] 2021-07-17 05:08
Sorry , I  dont know how to send pictures , So I  put one picture on Dropbox : https://www.dropbox.com/s/ckvndmci9vovcmy/21716.png?dl=0

**Comment by Da-Technomancer** [comment] 2021-07-19 12:55
Thank you for your report. 
This is now fixed in Essentials 2.11.1.

**Closed as completed by Da-Technomancer** 2021-07-19 12:55 UTC
Labels: bug
