### ISSUE TITLE
Auto-Crafter redstone changes

### ISSUE THREAD

**Issue by AlleCraft-alterego** [Da-Technomancer/Essentials#60] opened 2021-06-02 09:18 UTC
compatibility for comparator ( ingredients )

1 redstone tick = a recipe

continuous redstone impulse = continuous recipe making

auto imput / export ingredient / resoult from any invetory blocks

**Comment by Da-Technomancer** [comment] 2021-06-02 11:47
Duplicate of #56

**Closed as completed by Da-Technomancer** 2021-06-02 11:47 UTC
Labels: duplicate, enhancement

**Comment by AlleCraft-alterego** [comment] 2021-06-02 13:06
compatibility for comparator ?
