### ISSUE TITLE
[1.18.2] Crash when placing down an Industrial Crucible.

### ISSUE THREAD

**Issue by Gbergz** [Da-Technomancer/Essentials#75] opened 2022-05-06 17:59 UTC
**Describe the bug**
Crash when placing down a Industrial Crucible.

**To Reproduce**
1. Go ingame, world.
2. Grab a Industrial Crucible.
3. Crash.
4. See crash report below.

**Expected behavior [Optional]**
That the crash doesn't happen.

**Crash-Report**:
https://gist.github.com/Gbergz/55d1f5e1b99bbc1fb159747edabd4d28

**Versions**:
Minecraft: 1.18.2
Forge: 40.1.14
Crossroads: 2.7.5 | https://www.curseforge.com/minecraft/mc-mods/crossroads-mc/files/3781078
Essentials: 2.13.4 | https://www.curseforge.com/minecraft/mc-mods/essentials/files/3695751

**Comment by Da-Technomancer** [comment] 2022-05-06 18:22
I've transferred this issue, as I believe this is actually a bug with the Essentials code libraries which Crossroads uses, rather than Crossroads itself.
Having difficulty reproducing this issue, so a few questions:
- Is this a published modpack (so I can try seeing if it's something in an existing pack)?
- Does this happen every time?
- Is this only happening with the crucible or do other fluid machines from Crossroads/Essentials cause this crash?

**Comment by Gbergz** [comment] 2022-05-06 18:31
I've tested placing every block, only happens with the Industrial Crucible. This is my modpack: TNP Limitless 5, but it's an indev version of it, added Crossroads for the next update and did some testings. Found the crash when placing it.

It does not happen every time, only the first time you place it in a new world. Or for the very first time whenever.

**Comment by Da-Technomancer** [comment] 2022-05-06 19:04
![image](https://user-images.githubusercontent.com/11035641/167201373-a1f5612e-8ee9-41d3-a7ef-8bb2052243d1.png)
Either I've fixed the issue first try, or I simply can't reproduce it. 

Attached is a ZIP file with a special Essentials version. If you would, please try with that version of Essentials and let me know if the issue persists. 
Please send me a log file after testing with a crucible (just a regular log, not a crash or debug log), regardless of whether it works or not, and I'll know whether I've fixed your issue.

[essentials-1.18.2-2.13.5 - TNP compat.zip](https://github.com/Crossroads-Development/Essentials/files/8643101/essentials-1.18.2-2.13.5.-.TNP.compat.zip)

**Comment by Gbergz** [comment] 2022-05-06 20:20
Well, I don't crash anymore with that version.
**logs:**
[latest.log](https://github.com/Crossroads-Development/Essentials/files/8643425/latest.log)

**Comment by Da-Technomancer** [comment] 2022-05-06 21:33
Based on the results of the test and the logs, I believe this issue is fixed (though I never managed to reproduce it on my end). 

This issue should be fixed with the new Essentials version (1.18.2-2.13.5, now public). 
Please feel free to re-open this issue and post the logs if it re-occurs.

**Closed as completed by Da-Technomancer** 2022-05-06 21:33 UTC
Labels: bug
